# Site settings
title: Maikel's Blog
email: blog@maikel.uk
description: > # this means to ignore newlines until "baseurl:"
  Another blog of another Spaniard settled in the UK trying to grow roots in one of the most competitive cities in the world. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.maikel.uk" # the base hostname & protocol for your site
twitter_username: maikeldotuk
github_username:  maikeldotuk

# Build settings
markdown: kramdown
